name: Rubocop

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.0]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: check environment
        run: echo ${{ env.environment  }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - id: rubocop
        name: Run rubocop
        run: bundle exec rubocop -P
