name: Reusable workflow job

on:
  push:

jobs:
  reusable_rubocop_job_dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/rubocop.yml
        with:
          username: devUser
